apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-path: /app1/index.html
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/unhealthy-threshold-count: "2"
  name: {{ .Release.Name }}
spec:
  defaultBackend:
    service:
      name: {{ .Release.Name }}
      port:
        number: 80
  ingressClassName: my-aws-ingress-class